name: Gerar APK PAX PREVENIR
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Baixar codigo do projeto
        uses: actions/checkout@v4

      - name: Configurar Node.js (Versao Nova)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Inicializar Estrutura Nativa com CLI Atualizada
        run: npx @react-native-community/cli init PaxPrevenir --version 0.72.6 --skip-install

      - name: Organizar Pastas na Raiz
        run: |
          mv PaxPrevenir/android ./android
          mv PaxPrevenir/ios ./ios
          rm -rf PaxPrevenir

      - name: Instalar dependencias na Raiz
        run: npm install

      - name: Compilar o APK Final
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: App-PaxPrevenir-Instalavel
          path: android/app/build/outputs/apk/debug/app-debug.apk
